title: Bloody Enterprise

site:
  title: Bloody Enterprise

social:
  telegram: notesoncuffs

social_links:
  telegram: notesoncuffs

telegram_username: notesoncuffs

theme: minima

minima:
  skin: dark
